### ISSUE TITLE
Renew is not working

### ISSUE THREAD

**Issue by aytact** [m42e/certbot-dns-ispconfig#11]
Renewal configuration file domain.com.conf (cert: domain.com) produced an unexpected error: 'Namespace' object has no attribute 'certbot_dns_ispconfig:dns_ispconfig_propagation_seconds'. Skipping.

The error is being shown when we want to renew existing certificate.

**Comment by zxfrank** [comment]
Same here

Ubuntu 22.04.2 LTS
latest certbot snap, certbot 2.6.0

```
certbot._internal.renewal:Traceback was:
Traceback (most recent call last):
  File "/snap/certbot/3024/lib/python3.8/site-packages/certbot/_internal/renewal.py", line 502, in handle_renewal_request
    renewal_candidate = reconstitute(lineage_config, renewal_file)
  File "/snap/certbot/3024/lib/python3.8/site-packages/certbot/_internal/renewal.py", line 103, in reconstitute
    _restore_plugin_configs(config, renewalparams)
  File "/snap/certbot/3024/lib/python3.8/site-packages/certbot/_internal/renewal.py", line 173, in _restore_plugin_configs
    if config_item.startswith(plugin_prefix + "_") and not cli.set_by_cli(config_item):
  File "/snap/certbot/3024/lib/python3.8/site-packages/certbot/_internal/cli/__init__.py", line 505, in set_by_cli
    if not isinstance(getattr(detector, var), _Default):
AttributeError: 'Namespace' object has no attribute 'certbot_dns_ispconfig:dns_ispconfig_propagation_seconds'
```

**Comment by ahrasis** [comment]
Read: https://github.com/certbot/certbot/issues/9562

And also: https://community.letsencrypt.org/t/certbot-namespace-object-has-no-attribute-certbot-plugin-gandi-dns-credentials/204470

Other that, I think to use a dns plugin with certbot via snapd, it must be stored in snap store and then obtained via snapd as well. The developer should rewrite this plugin so that can be done and using this plugin with certbot that is installed via snapd will work.
